[project]
name = "counter"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
counter = "Counter111111111111111111111111111111111111" # placeholder; Anchor will replace or you can set your own..


